name: Deploy to Prod (main)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Authenticate to Prod Scratch Org
        run: |
          echo "${{ secrets.SF_PROD_SFDX_URL }}" > /tmp/prod_auth_url.txt
          sf org login sfdx-url --sfdx-url-file /tmp/prod_auth_url.txt --alias ebikes
          rm /tmp/prod_auth_url.txt

      - name: Deploy Metadata
        run: sf project deploy start --target-org ebikes --ignore-conflicts

      - name: Deploy Guest Profile Metadata
        run: sf project deploy start --metadata-dir=guest-profile-metadata -w 10 --target-org ebikes --ignore-conflicts

      - name: Publish Experience Cloud Site
        run: sf community publish -n E-Bikes --target-org ebikes
